# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vulnex < Formula
  desc "Multi-source vulnerability intelligence CLI"
  homepage "https://github.com/AnasSahel/vulnex"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.0.0/vulnex_1.0.0_darwin_amd64.tar.gz"
      sha256 "5e452eb32dcd48b75f3a31eda75c282536811cdb0389dae2a85c749179834ee5"

      define_method(:install) do
        bin.install "vulnex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.0.0/vulnex_1.0.0_darwin_arm64.tar.gz"
      sha256 "7efeed23696c219d617874c47e477512a8f24e2e72f10224af5fb20d574b0c27"

      define_method(:install) do
        bin.install "vulnex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.0.0/vulnex_1.0.0_linux_amd64.tar.gz"
      sha256 "4f94a54ede1b3f16cb9333b4b3fcfe6a7f4417088dc25befc167e8cb98d4f306"
      define_method(:install) do
        bin.install "vulnex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.0.0/vulnex_1.0.0_linux_arm64.tar.gz"
      sha256 "3a0c1c6968ca7698209ed8a5a0cd7e2f56db9ce9c77dd4301cd37ab98d0b56c1"
      define_method(:install) do
        bin.install "vulnex"
      end
    end
  end
end
