# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vulnex < Formula
  desc "Multi-source vulnerability intelligence CLI"
  homepage "https://github.com/AnasSahel/vulnex"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.4.0/vulnex_1.4.0_darwin_amd64.tar.gz"
      sha256 "e0183756e61e5fe8d66e883a3212eb1d0ecb49da5a12f7a0a6fae49a53c0979b"

      define_method(:install) do
        bin.install "vulnex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.4.0/vulnex_1.4.0_darwin_arm64.tar.gz"
      sha256 "6fe970a89b5d81ec692bea9e2936aafae5e3885843d71653a3ac044c78d4116a"

      define_method(:install) do
        bin.install "vulnex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.4.0/vulnex_1.4.0_linux_amd64.tar.gz"
      sha256 "8625922e2d60e37590006a89fda4af2b7c8d6309aad2d19a9309a9010d5aea2e"
      define_method(:install) do
        bin.install "vulnex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasSahel/vulnex/releases/download/v1.4.0/vulnex_1.4.0_linux_arm64.tar.gz"
      sha256 "74d148fcd7c8d5ba2fce527722c4ea7c9f2103c9c98f748cf880525b7e4b4d77"
      define_method(:install) do
        bin.install "vulnex"
      end
    end
  end
end
